#!/usr/bin/env bash

set -e

role=
env=

if [ "" != "local" ]; then
    echo "Caching configuration..."
    (cd /var/www/html && php artisan optimize)
fi

if [ "" = "app" ]; then
    exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
elif [ "" = "queue" ]; then
    echo "Running the queue..."
    php /var/www/html/artisan horizon
elif [ "" = "scheduler" ]; then
    while [ true ]
    do
      php /var/www/html/artisan schedule:run --verbose --no-interaction
      sleep 60
    done
else
    echo "Could not match the container role """
    exit 1
fi
